a=int(input("Enter an integer:"))
b=float(input("Enter a float value:"))
real=float(input("Enter real part of complex number:"))
imag=float(input("Enter imaginary part of complex number:"))
c=complex(real,imag)
print("integer:",a,"type:",type(a))
print("float:",b,"type:",type(b))
print("complex:",c,"type:",type(c))

x=int(input("enter first number:"))
y=int(input("enter second number:"))
print("addition:",x+y)
print("substraction:",x-y)
print("multiplication:",x*y)
print("division:",x/y)
print("floor division:",x//y)
print("modulo:",x%y)
print("Exponentiation:",x**y)
